# motion_blur.py
# Generated by ChatGPT

import numpy as np
import cv2
import random


class MotionBlurGenerator:
    """
    Module 1: Artificial motion blur (camera motion blur) for images.

    Supports:
        - Linear directional motion blur
        - Random jitter motion (camera shake)
        - Angular camera blur (rotational)
    """

    def __init__(self):
        pass

    # ------------------------------------------------------------
    # Linear motion blur
    # ------------------------------------------------------------
    def linear_motion_blur(self, image, length=15, angle=0):
        """
        Create linear motion blur using a motion blur kernel.

        length: how many pixels the blur extends
        angle: angle in degrees (0 = horizontal, 90 = vertical)
        """

        # Create a line kernel
        kernel = np.zeros((length, length))
        kernel[length // 2, :] = np.ones(length)
        kernel = kernel / length

        # Rotate kernel according to angle
        rotation_matrix = cv2.getRotationMatrix2D(
            (length // 2, length // 2),
            angle,
            1
        )
        kernel = cv2.warpAffine(kernel, rotation_matrix, (length, length))

        # Apply convolution
        blurred = cv2.filter2D(image, -1, kernel)
        return blurred

    # ------------------------------------------------------------
    # Randomized camera shake blur
    # ------------------------------------------------------------
    def camera_shake_blur(self, image, steps=8, max_length=10):
        """
        Simulates random handheld camera movement during exposure.

        steps: number of random movements
        max_length: max length of movement per step (pixels)
        """
        h, w = image.shape[:2]

        # Start from original
        accum = np.zeros_like(image, dtype=np.float32)

        for _ in range(steps):
            # Random motion direction
            dx = random.randint(-max_length, max_length)
            dy = random.randint(-max_length, max_length)

            # Create affine warp
            M = np.float32([[1, 0, dx], [0, 1, dy]])
            shifted = cv2.warpAffine(image, M, (w, h))

            accum += shifted.astype(np.float32)

        blurred = (accum / steps).astype(np.uint8)
        return blurred

    # ------------------------------------------------------------
    # Angular (rotational) blur
    # ------------------------------------------------------------
    def angular_blur(self, image, angle_range=15, steps=10):
        """
        Simulated camera rotation during exposure.

        angle_range: max rotation in degrees
        steps: number of intermediate exposures
        """
        h, w = image.shape[:2]
        center = (w // 2, h // 2)

        accum = np.zeros_like(image, dtype=np.float32)

        for i in range(steps):
            angle = random.uniform(-angle_range, angle_range)
            M = cv2.getRotationMatrix2D(center, angle, 1)
            rotated = cv2.warpAffine(image, M, (w, h))
            accum += rotated.astype(np.float32)

        blurred = (accum / steps).astype(np.uint8)
        return blurred

    # ------------------------------------------------------------
    # Master blur function
    # ------------------------------------------------------------
    def apply_blur(self,
                   image,
                   mode="linear",
                   **kwargs):
        """
        Main entry point.

        mode: "linear", "shake", or "angular"
        kwargs: parameters for each blur type
        """

        if mode == "linear":
            return self.linear_motion_blur(
                image,
                length=kwargs.get("length", 15),
                angle=kwargs.get("angle", 0)
            )

        elif mode == "shake":
            return self.camera_shake_blur(
                image,
                steps=kwargs.get("steps", 8),
                max_length=kwargs.get("max_length", 10)
            )

        elif mode == "angular":
            return self.angular_blur(
                image,
                angle_range=kwargs.get("angle_range", 15),
                steps=kwargs.get("steps", 10)
            )

        else:
            raise ValueError(f"Unknown blur mode '{mode}'")